"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { configureMarketplaceCommissionAction, updateCommissionObligationAction } from "@/lib/actions/marketplace-admin";
import type { MarketplaceCategory } from "@/lib/marketplace";

interface RuleRow { id: string; category_id: string | null; rate_percent: number; is_active: boolean; effective_from: string; service_categories?: { id: string; name_ar: string } | null; }
interface ObligationRow { id: string; booking_id: string; provider_id: string; gross_amount: number; rate_percent: number; commission_amount: number; currency: string; status: string; due_at: string | null; created_at: string; }

export default function AdminCommissionsClient({ rules, obligations, categories, isSuperAdmin }: { rules: RuleRow[]; obligations: ObligationRow[]; categories: MarketplaceCategory[]; isSuperAdmin: boolean }) {
  const router = useRouter(); const [categoryId, setCategoryId] = useState(""); const [rate, setRate] = useState(""); const [message, setMessage] = useState("");
  const configure = async () => { const result = await configureMarketplaceCommissionAction(categoryId || null, Number(rate)); if (!result.success) setMessage(result.error || "تعذر الحفظ"); else { setMessage(""); setRate(""); router.refresh(); } };
  const update = async (id: string, status: "SETTLED" | "DISPUTED" | "VOID") => { const result = await updateCommissionObligationAction(id, status); if (!result.success) setMessage(result.error || "تعذر التحديث"); else router.refresh(); };
  return <div className="space-y-6">
    <section className="surface-card p-5"><h2 className="font-black">قواعد العمولة</h2><p className="mt-1 text-xs text-muted">لا توجد نسبة افتراضية مخفية. يجب أن يعتمد المدير الأعلى نسبة عامة أو خاصة، وتُحفظ لقطة عند المعاملة.</p>{isSuperAdmin ? <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><select value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="form-field"><option value="">نسبة عامة لكل السوق</option>{categories.map((parent) => <optgroup key={parent.id} label={parent.name_ar}><option value={parent.id}>{parent.name_ar}</option>{(parent.children || []).map((child) => <option key={child.id} value={child.id}>{child.name_ar}</option>)}</optgroup>)}</select><input value={rate} onChange={(event) => setRate(event.target.value)} type="number" min="0" max="100" step="0.01" placeholder="النسبة %" className="form-field" /><button type="button" onClick={configure} className="brand-button">اعتماد القاعدة</button></div> : <p className="mt-4 text-xs text-[rgb(var(--warning))]">عرض فقط: تعديل قواعد العمولة محصور بالمدير الأعلى.</p>}{message && <p role="alert" className="mt-3 text-xs text-[rgb(var(--danger))]">{message}</p>}<div className="mt-4 flex flex-wrap gap-2">{rules.map((rule) => <span key={rule.id} className="status-pill bg-surface-muted">{rule.service_categories?.name_ar || "كل السوق"}: {rule.rate_percent}% {rule.is_active ? "نشطة" : "مؤرشفة"}</span>)}</div></section>
    <section className="surface-card overflow-hidden"><div className="border-b border-theme p-4"><h2 className="font-black">التزامات العمولات</h2></div>{obligations.length ? <div className="divide-y divide-[rgb(var(--border))]">{obligations.map((item) => <div key={item.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><strong className="text-sm">حجز #{item.booking_id.slice(0, 8)}</strong><p className="mt-1 text-[11px] text-muted">إجمالي {item.gross_amount} د.أ · لقطة {item.rate_percent}% · عمولة {item.commission_amount} د.أ</p></div><span className="status-pill bg-surface-muted">{item.status}</span><div className="flex gap-1">{item.status === "DUE" && <button type="button" onClick={() => update(item.id, "SETTLED")} className="brand-button !min-h-8 !px-3 !py-1 text-xs">تسوية</button>}{["PENDING", "DUE"].includes(item.status) && <button type="button" onClick={() => update(item.id, "DISPUTED")} className="secondary-button !min-h-8 !px-3 !py-1 text-xs">نزاع</button>}</div></div>)}</div> : <p className="p-10 text-center text-sm text-muted">لا توجد التزامات عمولة بعد.</p>}</section>
  </div>;
}

